# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "babashka-linux",
    build_file_content = """exports_files(["bb"])""",
    url = "https://github.com/babashka/babashka/releases/download/v0.4.6/babashka-0.4.6-linux-amd64-static.tar.gz",
    sha256 = "aac1be5a441945ebcc6042d2283ac26399895da090437f84123a3124b72fb25a",
)

http_archive(
    name = "babashka-macos",
    build_file_content = """exports_files(["bb"])""",
    url = "https://github.com/babashka/babashka/releases/download/v0.4.6/babashka-0.4.6-macos-amd64.tar.gz",
    sha256 = "8fd778592b0f821b69096fbbb9838f7b24c0f9090e68d0296098facab79d7c5a",
)

register_toolchains(
    "//:bb_linux_toolchain",  # (1)
    "//:bb_macos_toolchain",
)
